"use client";

import * as React from "react";
import { isoTime } from "@/components/console";
import { calendarDate, clockTime, timeZoneLabel } from "../alert-lifecycle";

/**
 * What this is and when it was made — the line a printed copy is filed under,
 * and the PRD's standing disclosure (§6) on the one surface in the product that
 * leaves the building.
 */
export function ReportFooter({ generatedAt }: { generatedAt: number }) {
  return (
    <footer className="mt-2 flex flex-wrap items-baseline justify-between gap-x-6 gap-y-1 border-t border-line pt-5 text-label tracking-normal text-ink-soft">
      <span>Simulated data · generated by Fleet Console</span>
      <time dateTime={isoTime(generatedAt)} className="tnum">
        Generated {calendarDate(generatedAt)}, {clockTime(generatedAt)}{" "}
        {timeZoneLabel(generatedAt)}
      </time>
    </footer>
  );
}

/**
 * Stamped once, at open. A generated-at line driven by the shared ticker would
 * advance while the reader is on the page, which is the one thing a document's
 * own timestamp must not do.
 */
export function useGeneratedAt(): number {
  const [generatedAt] = React.useState(() => Date.now());
  return generatedAt;
}
